/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.zapataluis.tiendapoo.correcion.view;

import com.zapataluis.tiendapoo.correcion.model.Producto;
import com.zapataluis.tiendapoo.correcion.model.Venta;
import com.zapataluis.tiendapoo.correcion.model.Cliente;
import com.zapataluis.tiendapoo.correcion.model.DetalleVenta;
import com.zapataluis.tiendapoo.servicio.IClienteServicio;
import com.zapataluis.tiendapoo.servicio.IProductoServicio;
import com.zapataluis.tiendapoo.servicio.IVentaServicio;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class PanelVenta extends javax.swing.JPanel {

    
    
    private final DefaultTableModel modeloCarrito;
    private final DefaultTableModel modeloVentas;
    private final IClienteServicio clienteServicio;
    private final IProductoServicio productoServicio;
    private final IVentaServicio ventaServicio;
    private final ArrayList<DetalleVenta> carritoTemporal = new ArrayList<>();

   
    private Cliente clienteActual = null;

    public PanelVenta(IClienteServicio clienteServicio,IProductoServicio productoServicio,IVentaServicio ventaServicio) {
         this.clienteServicio = clienteServicio;
         this.productoServicio = productoServicio;
         this.ventaServicio = ventaServicio;
        initComponents();
        txtId.setPreferredSize(new java.awt.Dimension(200, 25));
        txtCantidad.setPreferredSize(new java.awt.Dimension(200, 25));
        txtNombreProducto.setPreferredSize(new java.awt.Dimension(200, 25));

        // Configurar tabla carrito
        modeloCarrito = new DefaultTableModel();
        modeloCarrito.addColumn("Producto");
        modeloCarrito.addColumn("Talla");
        modeloCarrito.addColumn("Color");
        modeloCarrito.addColumn("Precio unit");
        modeloCarrito.addColumn("Cantidad");
        modeloCarrito.addColumn("Subtotal");
        tablaCarrito.setModel(modeloCarrito);

        // Configurar tabla historial de ventas
        modeloVentas = new DefaultTableModel();
        modeloVentas.addColumn("ID venta");
        modeloVentas.addColumn("Cliente");
        modeloVentas.addColumn("Productos");
        modeloVentas.addColumn("Total");
        tableVenta.setModel(modeloVentas);

        cargarTablaVentas();
    }
    public void cargarTablaVentas() {
        modeloVentas.setRowCount(0);
        for (Venta v : ventaServicio.getVentas()) {
            Object[] fila = {
                v.getId(),
                v.getCliente().getNombre(),
                v.getSobreLaVenta().size() + " producto(s)",
                "$" + v.getTotal()
            };
            modeloVentas.addRow(fila);
        }
    }

    // Actualiza la tabla del carrito con los productos temporales
    private void actualizarTablaCarrito() {
        modeloCarrito.setRowCount(0);
        for (DetalleVenta s : carritoTemporal) {
            Producto p = s.getProducto();
            double subtotal = p.getPrecio() * s.getCantidad();
            Object[] fila = {
                p.getNombre(),
                p.getTalla(),
                p.getColor(),
                p.getPrecio(),
                s.getCantidad(),
                subtotal
            };
            modeloCarrito.addRow(fila);
        }
    }

    private void limpiarVenta() {
        carritoTemporal.clear();
        clienteActual = null;
        txtId.setText("");
        txtCantidad.setText("");
        txtNombreProducto.setText("");
        actualizarTablaCarrito();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelidusuario = new javax.swing.JLabel();
        labelseparadorcliente = new javax.swing.JLabel();
        labelseparadorventa = new javax.swing.JLabel();
        labelCantidad = new javax.swing.JLabel();
        labelNombreproducto = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtNombreProducto = new javax.swing.JTextField();
        btnCarritoV = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCarrito = new javax.swing.JTable();
        labelCarrito = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableVenta = new javax.swing.JTable();
        btnLimpiar = new javax.swing.JButton();
        btnRegistrarV = new javax.swing.JButton();

        labelidusuario.setText("Ingrese su id de usuario:");

        labelseparadorcliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelseparadorcliente.setText("Cliente");

        labelseparadorventa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelseparadorventa.setText("Venta");

        labelCantidad.setText("Cantidad:");

        labelNombreproducto.setText("Nombre del producto:");

        txtId.addActionListener(this::txtIdActionPerformed);

        btnCarritoV.setBackground(new java.awt.Color(255, 255, 0));
        btnCarritoV.setText("Agregar al carrito");
        btnCarritoV.addActionListener(this::btnCarritoVActionPerformed);

        tablaCarrito.setBackground(new java.awt.Color(204, 204, 255));
        tablaCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Producto", "Talla", "Color", "Precio unit", "Cantidad", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaCarrito);

        labelCarrito.setText("Carrito");

        tableVenta.setBackground(new java.awt.Color(204, 204, 255));
        tableVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID venta", "Cliente", "Productos", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableVenta);

        btnLimpiar.setBackground(new java.awt.Color(51, 204, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        btnRegistrarV.setBackground(new java.awt.Color(0, 255, 0));
        btnRegistrarV.setText("Registrar Venta");
        btnRegistrarV.addActionListener(this::btnRegistrarVActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelseparadorcliente)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(labelNombreproducto)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(labelCantidad)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(labelseparadorventa, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(labelidusuario)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(btnCarritoV))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelCarrito)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnLimpiar)))
                            .addComponent(btnRegistrarV))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelCarrito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelseparadorcliente)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelidusuario)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(labelseparadorventa)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCantidad)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNombreproducto)
                            .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnCarritoV))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiar)))
                .addGap(10, 10, 10)
                .addComponent(btnRegistrarV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnCarritoVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarritoVActionPerformed
      
        try {
            int idUsuario = Integer.parseInt(txtId.getText().trim());
            int cantidad = Integer.parseInt(txtCantidad.getText().trim());
            String nombre = txtNombreProducto.getText().trim();

           clienteActual = clienteServicio.buscarClientePorId(idUsuario);
           Producto p = productoServicio.buscarProductoPorNombre(nombre);
           
           
           
           if (clienteActual == null) {
              JOptionPane.showMessageDialog(this, "Cliente no encontrado.");
               return;
            }

           
             if (p== null) {
             JOptionPane.showMessageDialog(this, "Producto no encontrado.");
             return;
            }

           // Verificar stock acumulado en carrito (bug de doble reserva)
           int yaEnCarrito = carritoTemporal.stream()
           .filter(d -> d.getProducto().getId() == p.getId())
           .mapToInt(DetalleVenta::getCantidad)
           .sum();
           if (cantidad + yaEnCarrito > p.getStock()) {
             JOptionPane.showMessageDialog(this, "Stock insuficiente. Ya tienes " + yaEnCarrito + " en carrito.");
             return;
           }

            carritoTemporal.add(new DetalleVenta(p, cantidad)); 
            actualizarTablaCarrito();
            txtCantidad.setText("");
            txtNombreProducto.setText("");
            JOptionPane.showMessageDialog(this, "Producto agregado al carrito.");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID y cantidad deben ser números válidos.");
        }
    }//GEN-LAST:event_btnCarritoVActionPerformed

    private void btnRegistrarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVActionPerformed
          
        if (clienteActual == null) {
            JOptionPane.showMessageDialog(this, "Primero busca un cliente por ID.");
            return;
        }
        if (carritoTemporal.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El carrito está vacío. Agrega productos primero.");
            return;
        }

        boolean exito = ventaServicio.registrarVenta(clienteActual, carritoTemporal);
        if (exito) {
            JOptionPane.showMessageDialog(this, "Venta registrada correctamente.");
            cargarTablaVentas();
            limpiarVenta();
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar la venta. Verifica el stock.");
        }
                                
    }//GEN-LAST:event_btnRegistrarVActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarVenta();
    }//GEN-LAST:event_btnLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarritoV;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrarV;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelCantidad;
    private javax.swing.JLabel labelCarrito;
    private javax.swing.JLabel labelNombreproducto;
    private javax.swing.JLabel labelidusuario;
    private javax.swing.JLabel labelseparadorcliente;
    private javax.swing.JLabel labelseparadorventa;
    private javax.swing.JTable tablaCarrito;
    private javax.swing.JTable tableVenta;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombreProducto;
    // End of variables declaration//GEN-END:variables
}
