/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.zapataluis.tiendapoo.correcion.view;

import com.zapataluis.tiendapoo.servicio.IClienteServicio;
import com.zapataluis.tiendapoo.servicio.IProductoServicio;
import com.zapataluis.tiendapoo.servicio.IVentaServicio;
import com.zapataluis.tiendapoo.servicio.impl.ClienteServicio;
import com.zapataluis.tiendapoo.servicio.impl.ProductoService;
import com.zapataluis.tiendapoo.servicio.impl.VentaServicio;
import java.util.logging.Level;


public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());
    private IClienteServicio clienteServicio;
    private IProductoServicio productoServicio;
    private IVentaServicio ventaServicio;
    
    public VentanaPrincipal() {
        clienteServicio = new ClienteServicio();
        productoServicio = new ProductoService();
         ventaServicio = new VentaServicio();
        initComponents();
        
   PanelVentanaPrincipal.addTab("Clientes",  new PanelClientes(clienteServicio));
   PanelVentanaPrincipal.addTab("Productos", new PanelProducto(productoServicio));
   PanelVentanaPrincipal.addTab("Ventas",    new PanelVenta(clienteServicio, productoServicio, ventaServicio));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelVentanaPrincipal = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelVentanaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelVentanaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane PanelVentanaPrincipal;
    // End of variables declaration//GEN-END:variables
}
